### ISSUE TITLE
Is it possible to have versioning via lang AND git tag?

### ISSUE THREAD

**Issue by ghuntley** [GitbookIO/plugin-versions#2]
ReactiveUI would like to have "$lang/$tag/index.html", right now it looks like it's a either or situation ie. "$lang/index.html" or "$tag/index.html"

Related issue: https://github.com/reactiveui/documentation/issues/11

**Comment by SamyPesse** [comment]
You can use languages or tags as versions with this plugin:

``` js
{
    "plugins": [ "versions" ],
    "pluginsConfig": {
        "versions": {
            "type": "tags"
        }
    }
}
```

or 

``` js
{
    "plugins": [ "versions" ],
    "pluginsConfig": {
        "versions": {
            "type": "languages"
        }
    }
}
```

It used the APIs:
- https://api.gitbook.com/book/reactiveui/documentation/versions/languages
- https://api.gitbook.com/book/reactiveui/documentation/versions/tags
- https://api.gitbook.com/book/reactiveui/documentation/versions/branches

(The Tags API is failing with a 500 since there is no tags in your repo, we are working on fixing it, but it'll list a tag once you've published one).

It also looks like [your list of languages](https://github.com/reactiveui/documentation/blob/master/LANGS.md) is invalid, there is `English`, then `css` and `js`.

:)

**Comment by SamyPesse** [comment]
Sorry I think I misunderstood your issue, you want to mix tags and languages as versions ?

**Comment by ghuntley** [comment]
> re: invalid languages

That's deliberate to work around https://github.com/GitbookIO/gitbook/issues/744 - more details over at https://github.com/reactiveui/documentation/issues/1 

> re: the actual issue.

Sorry I should have been more clear, we would like to mix languages and tags.

For purely illustrative reasons:

```
/en/index.html (latest)
/en/history/v1.1.0/index.html (tag)

/jp/index.html (latest)
/jp/history/v1.1.0/index.html (tag)
```

The UX would be when the user visits the documentation for the first time they select language (already implemented in gitbook) THEN once they have selected the language a dropbown exists to allow them to see a version of the doc (latest or tag) in their selected language.

**Comment by SamyPesse** [comment]
> re: invalid languages

GitBook 3.0.0 will fix this, and also be more adapted for documentation inside repository (for example inside a `docs` folder).

> re: the actual issue.

GitBook.com can already serve older versions: `http://docs.reactiveui.net/v/<sha | tag | branch>/<filename>`
(ex: http://docs.reactiveui.net/v/120a3189233540a82d3b02cfe018ce1f80ca6794/en/index.html)

But this plugin can't currently correctly build the list of versions for your usecase (each version will redirect to the languages selector).

I think it can be fixed in this plugin: https://github.com/GitbookIO/plugin-versions/blob/master/assets/plugin.js#L53 by adding: `+ (gitbook.innerLanguage? gitbook.innerLanguage+'/' : '') + gitbook.state.filepath`; I'll make the changes in a few hours.

**Comment by ghuntley** [comment]
:star2: :star: :star2: 

I didn't know about the /v/[sha|tag|branch] thanks for sharing that and cheers for fixing up L53.

**Comment by SamyPesse** [comment]
Done,

You need to change your `book.json` to merge with:

``` js
{
    "plugins": [ "versions" ],
    "pluginsConfig": {
        "versions": {
            "type": "tags"
        }
    }
}
```

(And also push a first tag ;) )

**Comment by ghuntley** [comment]
:sparkling_heart:
